- hosts: localhost
  remote_user: root
  tasks:
  - name:  git install
    yum: state=present name=git
    become: yes
    become_method: sudo
  - name:  install docker 
    yum: state=latest name=docker
    become: yes
    become_method: sudo
  - name: check docker service is on
    service: name=docker enabled=yes state=started
    become: yes
    become_method: sudo
  - name: give user permissions
    user: 
      name=ec2-user
      groups=docker
      append=yes
    become: yes
    become_method: sudo
  - name: git clone Petclinic
    git:
      clone=yes
      dest=/home/ec2-user/petclinic
      repo=https://github.com/YaronBasson/spring-petclinic.git
  - name: clone trepo repo
    git:
      clone=yes
      update=no
      dest=/home/ec2-user/trepo
      repo=https://github.com/YaronBasson/trepo.git
  - name: install maven
    unarchive: copy=no creates=~/apache-maven-3.3.9 dest=~ src=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
