FROM centos:6.8
MAINTAINER Yaron Basson
RUN yum install -y wget && wget http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz && tar xvfz apache-maven-3.3.9-bin.tar.gz
